### ISSUE TITLE
Can't boot with my RX5600XT

### ISSUE THREAD

**Issue by Knives79** [RobyRew/ASRock_Fatality_AB350_Gaming-ITX_Hackintosh#4]
Hi, I tried your EFI, I have an RX5600XT, I simply added the agdpmod=pikera flag in the booter, but I can't pass the apple logo.

**Comment by RobyRew** [comment]
I have custom patches for RX560, you have to replace those with some generated with AGPMInjector, Download it from here and edit your EFI with only that kext:
https://github.com/RobyRew/AGPMInjector
